"""Baseline schema.

Revision ID: b0001_baseline
Revises:
Create Date: 2026-09-22
"""
from __future__ import annotations

from alembic import op

from app.database import Base
from app import models  # noqa: F401  (register mappers)

revision = "b0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Baseline: create the full current schema. Subsequent changes should be
    # autogenerated against the models (`alembic revision --autogenerate`).
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
